inherit_from: .rubocop_todo.yml

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb' # TODO: deprecated

Metrics/AbcSize:
  Exclude:
    - lib/tasks/**
    - spec/**/**
    - app/models/funder.rb # TODO: deprecated
    - app/models/funder_attribute.rb # TODO: deprecated
    - test/**/** # TODO: deprecated

Metrics/BlockLength:
  Exclude:
    - app/admin/*
    - config/**/**
    - lib/tasks/**
    - spec/**/**
    - Guardfile
    - test/**/** # TODO: deprecated

Metrics/ClassLength:
  Exclude:
    - spec/**/**
    - app/models/beneficiary.rb
    - app/models/funder.rb # TODO: deprecated
    - app/models/funder_attribute.rb # TODO: deprecated

Metrics/LineLength:
  Exclude:
    - Gemfile
    - bin/spring
    - config/**/**
    - lib/tasks/**
    # - spec/**/**
    - app/models/funder.rb # TODO: deprecated
    - app/models/funder_attribute.rb # TODO: deprecated
    - app/models/profile.rb # TODO: deprecated
    - test/**/** # TODO: deprecated

Metrics/MethodLength:
  Exclude:
    - spec/**/**
    - lib/tasks/**
    - app/models/funder.rb # TODO: deprecated
    - app/models/funder_attribute.rb # TODO: deprecated
    - test/**/** # TODO: deprecated

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/*/**
    - lib/tasks/transfer.rake
