inherit_from: .rubocop_todo.yml

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/tasks/**
    - spec/**/**

Metrics/BlockLength:
  Exclude:
    - app/admin/*
    - config/**/**
    - lib/tasks/**
    - spec/**/**

Metrics/LineLength:
  Exclude:
    - Gemfile
    - bin/spring
    - config/**/**
    - lib/tasks/**
    - app/admin/**

Metrics/MethodLength:
  Exclude:
    - spec/**/**
    - lib/tasks/**

Rails/SkipsModelValidations:
  Exclude:
    - spec/**/**

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/*/**
    - lib/tasks/transfer.rake
