---
version: 2
jobs:
  build:
    working_directory: ~/beehive-giving
    parallelism: 1
    docker:
      - image: circleci/ruby:2.4-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: beehive-giving
          RAILS_ENV: test
      - image: postgres:9.6
        environment:
          POSTGRES_USER: beehive-giving
          POSTGRES_DB: beehive_giving_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        keys:
          - gem-cache-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - gem-cache-{{ .Branch }}
          - gem-cache

      # Restore yarn cache
      - type: cache-restore
        keys:
          - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-cache-{{ .Branch }}
          - yarn-cache

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      - run:
          name: Yarn Install
          command: bin/yarn install

      # Store bundle cache
      - type: cache-save
        key: gem-cache-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Store yarn cache
      - type: cache-save
        key: yarn-cache-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - run:
          name: Wait for Database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:setup --trace

      - run:
          name: Run Ruby unit and integration tests
          command: bundle exec rspec --profile 10 --format progress

      - run:
          name: Run Javascript unit tests
          command: bin/yarn test